name: Example Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 25 * *" # Runs every Month 25th date 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a test script
        run: echo "Hello, GitHub Actions!"
